#!/bin/bash
# ═══════════════════════════════════════════════════
# EthicFlow — Setup Wizard
# Run once when deploying for a new institution
# Usage: chmod +x setup.sh && ./setup.sh
# ═══════════════════════════════════════════════════

set -e

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║         EthicFlow — Setup Wizard                ║"
echo "║         מערכת ניהול ועדת אתיקה                  ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ─── Check prerequisites ───
echo "🔍 Checking prerequisites..."
command -v docker >/dev/null 2>&1 || { echo "❌ Docker is required. Install: https://docs.docker.com/get-docker/"; exit 1; }
command -v docker compose version >/dev/null 2>&1 || { echo "❌ Docker Compose V2 is required."; exit 1; }
command -v node >/dev/null 2>&1 || { echo "❌ Node.js is required. Install: https://nodejs.org/"; exit 1; }
echo "✅ All prerequisites met"
echo ""

# ─── Institution Details ───
echo "📋 Institution Details"
echo "──────────────────────"
read -p "Institution name (Hebrew): " INST_NAME_HE
read -p "Institution name (English): " INST_NAME_EN
read -p "Domain (e.g., ethics.jct.ac.il): " INST_DOMAIN
read -p "Primary color hex (default: #1e40af): " INST_COLOR
INST_COLOR=${INST_COLOR:-#1e40af}
read -p "Default language (he/en, default: he): " INST_LANG
INST_LANG=${INST_LANG:-he}
echo ""

# ─── Database ───
echo "🗄️ Database"
echo "──────────────────────"
read -p "DB name (default: ethicflow): " DB_NAME
DB_NAME=${DB_NAME:-ethicflow}
read -p "DB user (default: ethicflow): " DB_USER
DB_USER=${DB_USER:-ethicflow}
read -sp "DB password: " DB_PASSWORD
echo ""
if [ -z "$DB_PASSWORD" ]; then
  DB_PASSWORD=$(openssl rand -hex 16)
  echo "  Generated password: $DB_PASSWORD"
fi
echo ""

# ─── JWT Secret ───
JWT_SECRET=$(openssl rand -hex 32)
echo "🔐 Generated JWT secret: ${JWT_SECRET:0:8}..."
echo ""

# ─── Email ───
echo "📧 Email Configuration"
echo "──────────────────────"
echo "  1) Console (prints to terminal — for testing)"
echo "  2) SMTP (production email)"
read -p "Choose (1/2, default: 1): " EMAIL_CHOICE
EMAIL_CHOICE=${EMAIL_CHOICE:-1}

SMTP_HOST=""
SMTP_PORT=""
SMTP_USER=""
SMTP_PASSWORD=""
SMTP_FROM=""

if [ "$EMAIL_CHOICE" = "2" ]; then
  read -p "SMTP host: " SMTP_HOST
  read -p "SMTP port (default: 587): " SMTP_PORT
  SMTP_PORT=${SMTP_PORT:-587}
  read -p "SMTP user: " SMTP_USER
  read -sp "SMTP password: " SMTP_PASSWORD
  echo ""
  read -p "From email: " SMTP_FROM
fi
echo ""

# ─── Admin User ───
echo "👤 Admin User (first user)"
echo "──────────────────────"
read -p "Admin email: " ADMIN_EMAIL
read -p "Admin full name: " ADMIN_NAME
read -sp "Admin password: " ADMIN_PASSWORD
echo ""
echo ""

# ─── Environment ───
echo "🌐 Environment"
echo "──────────────────────"
echo "  1) Development (localhost)"
echo "  2) Production (with domain)"
read -p "Choose (1/2, default: 1): " ENV_CHOICE
ENV_CHOICE=${ENV_CHOICE:-1}

if [ "$ENV_CHOICE" = "1" ]; then
  NODE_ENV="development"
  FRONTEND_URL="http://localhost:5173"
  API_PORT=5000
  WEB_PORT=5173
  DB_HOST="localhost"
else
  NODE_ENV="production"
  FRONTEND_URL="https://${INST_DOMAIN}"
  API_PORT=3000
  WEB_PORT=80
  DB_HOST="db"
fi

# ─── Generate .env ───
echo ""
echo "📝 Generating .env file..."

cat > .env << EOF
# ═══════════════════════════════════════════════════
# EthicFlow — Generated by setup.sh on $(date +%Y-%m-%d)
# Institution: ${INST_NAME_EN}
# ═══════════════════════════════════════════════════

NODE_ENV=${NODE_ENV}

# Database
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_HOST=${DB_HOST}
DB_PORT=5432
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}

# pgAdmin (dev only)
PGADMIN_EMAIL=admin@ethicflow.dev
PGADMIN_PASSWORD=admin123

# JWT
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=8h

# Ports
API_PORT=${API_PORT}
WEB_PORT=${WEB_PORT}
FRONTEND_URL=${FRONTEND_URL}

# Institution
INSTITUTION_NAME_HE=${INST_NAME_HE}
INSTITUTION_NAME_EN=${INST_NAME_EN}
INSTITUTION_LOGO=/logos/default.png
INSTITUTION_PRIMARY_COLOR=${INST_COLOR}
INSTITUTION_DOMAIN=${INST_DOMAIN}
DEFAULT_LANGUAGE=${INST_LANG}

# Services (change as needed)
AI_PROVIDER=mock
EMAIL_PROVIDER=$([ "$EMAIL_CHOICE" = "2" ] && echo "smtp" || echo "console")
STORAGE_PROVIDER=local
CALENDAR_PROVIDER=internal
AUTH_PROVIDER=local

# SMTP
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASSWORD=${SMTP_PASSWORD}
SMTP_FROM=${SMTP_FROM}
SMTP_FROM_NAME=ועדת אתיקה — ${INST_NAME_HE}

# SLA
SLA_TRIAGE_DAYS=3
SLA_REVIEW_DAYS=14
SLA_REVISION_DAYS=30
SLA_APPROVAL_DAYS=5
SLA_WARNING_HOURS=48

# Security
BCRYPT_ROUNDS=12
RATE_LIMIT_MAX=100
LOGIN_RATE_LIMIT_MAX=5
SESSION_TIMEOUT_MINUTES=30
EOF

echo "✅ .env created"

# ─── Start Services ───
echo ""
echo "🐳 Starting Docker services..."
if [ "$ENV_CHOICE" = "1" ]; then
  docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d
else
  docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
fi

echo "⏳ Waiting for database..."
sleep 5

# ─── Install Dependencies ───
echo ""
echo "📦 Installing dependencies..."
cd backend && npm install
cd ../frontend && npm install
cd ..

# ─── Run Migrations ───
echo ""
echo "🗄️ Running database migrations..."
cd backend
npx prisma migrate deploy
echo "✅ Migrations complete"

# ─── Seed Admin User ───
echo ""
echo "👤 Creating admin user..."
npx prisma db seed -- --admin-email="${ADMIN_EMAIL}" --admin-name="${ADMIN_NAME}" --admin-password="${ADMIN_PASSWORD}"
echo "✅ Admin user created"
cd ..

# ─── Done ───
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║              ✅ Setup Complete!                  ║"
echo "╠══════════════════════════════════════════════════╣"
echo "║                                                  ║"
if [ "$ENV_CHOICE" = "1" ]; then
echo "║  Start backend:  cd backend && npm run dev       ║"
echo "║  Start frontend: cd frontend && npm run dev      ║"
echo "║  pgAdmin:        http://localhost:5050            ║"
echo "║  App:            http://localhost:5173            ║"
else
echo "║  App:            https://${INST_DOMAIN}          ║"
fi
echo "║                                                  ║"
echo "║  Login:          ${ADMIN_EMAIL}                  ║"
echo "║                                                  ║"
echo "╚══════════════════════════════════════════════════╝"
