/**
 * EthicFlow E2E — researcher submission flow in UI.
 */

import { test, expect } from '../support/fixtures'
import { hasRoleCredentials } from '../support/credentials'
import { loginViaUi, gotoAuthed } from '../support/ui-helpers'

test('researcher can fill required fields and submit', async ({ page }) => {
  test.skip(!hasRoleCredentials('RESEARCHER'), 'RESEARCHER credentials are not configured')
  await loginViaUi(page, 'RESEARCHER')
  await gotoAuthed(page, '/submissions/new')

  const title = `PW UI Submission ${Date.now()}`
  await page.getByTestId('field-input-researchTitle').fill(title)
  await page.getByTestId('field-input-researchType').selectOption('clinical')
  await page.getByTestId('field-input-startDate').fill('2026-12-01')
  await page.getByTestId('field-input-description').fill(
    'This submission is generated by Playwright UI flow and includes enough text to pass minimum validation constraints.'
  )

  await page.getByTestId('submit-save-draft').click()
  await expect(page.getByTestId('submit-save-draft')).toBeVisible()

  await page.getByTestId('submit-final-submit').click()
  await expect(page.getByTestId('submit-success-screen')).toBeVisible()
})
