/**
 * Ethic-Net — local PDF preview generator.
 * Generates six sample PDFs (approval + protocol in he/en/both).
 */

import path from 'path'
import fs from 'fs/promises'
import { getDefaultApprovalTemplate } from '../src/constants/approvalTemplate.js'
import { renderHtmlToPdf } from '../src/services/pdf/renderer.js'
import { buildHeHtml, buildEnHtml, buildBilingualHtml } from '../src/services/pdf/templates/approvalLetter.js'
import { buildProtocolHtml, buildBilingualProtocolHtml } from '../src/services/pdf/templates/protocol.js'

const outputDir = path.resolve('generated', 'previews')

const approvalSubmission = {
  applicationId: 'ETH-2026-1001',
  title: 'Clinical AI Evaluation',
  updatedAt: new Date('2026-04-19T12:00:00Z'),
  author: { fullName: 'Dr. Noam Levi', email: 'noam@example.com' },
}

const approvalHeCtx = {
  applicationId: 'ETH-2026-1001',
  researchTitle: 'בדיקת בינה מלאכותית קלינית',
  trackLabel: 'מסלול מלא',
  issueDate: '20/04/2026',
  approvedDate: '19/04/2026',
  validUntil: '19/04/2027',
  researcherName: 'ד"ר נועם לוי',
  researcherEmail: 'noam@example.com',
  institutionName: 'המרכז האקדמי לב',
}

const approvalEnCtx = {
  applicationId: 'ETH-2026-1001',
  researchTitle: 'Clinical AI Evaluation',
  trackLabel: 'Full Review',
  issueDate: '20 April 2026',
  approvedDate: '19 April 2026',
  validUntil: '19 April 2027',
  researcherName: 'Dr. Noam Levi',
  researcherEmail: 'noam@example.com',
  institutionName: 'Lev Academic Center',
}

const protocol = {
  id: 'protocol-preview-1',
  title: 'פרוטוקול ועדת אתיקה אפריל 2026',
  contentJson: {
    sections: [
      { heading: 'פתיחה', content: 'הישיבה נפתחה בשעה 09:00.' },
      { heading: 'דיון והחלטות', content: 'הבקשה ETH-2026-1001 אושרה.\nהמשך מעקב בעוד 6 חודשים.' },
    ],
  },
  signatures: [
    { status: 'SIGNED', user: { fullName: 'ד"ר מרים כהן' } },
    { status: 'PENDING', user: { fullName: 'Prof. Daniel Katz' } },
  ],
}

const protocolContext = {
  brandPrimary: '#1e3a5f',
  he: {
    issueDate: 'הופק: 20/04/2026',
    meetingDate: '19/04/2026',
    statusLabel: 'ממתין לחתימות',
    titleLabel: 'פרוטוקול ועדת אתיקה',
    meetingLabel: 'תאריך ישיבה',
    statusFieldLabel: 'סטטוס',
    footer: 'מסמך זה הופק על ידי מערכת Ethic-Net • 20/04/2026',
    institutionName: 'המרכז האקדמי לב',
  },
  en: {
    issueDate: 'Generated: 20 April 2026',
    meetingDate: '19 April 2026',
    statusLabel: 'Pending Signatures',
    titleLabel: 'Ethics Committee Protocol',
    meetingLabel: 'Meeting Date',
    statusFieldLabel: 'Status',
    footer: 'Generated by Ethic-Net • 20 April 2026',
    institutionName: 'Lev Academic Center',
  },
}

/**
 * Generates all preview files.
 * @returns {Promise<void>}
 */
async function generatePreviews() {
  await fs.mkdir(outputDir, { recursive: true })
  const files = [
    {
      file: 'approval-he.pdf',
      html: buildHeHtml(approvalSubmission, getDefaultApprovalTemplate('he'), approvalHeCtx, '', '#1e3a5f'),
    },
    {
      file: 'approval-en.pdf',
      html: buildEnHtml(approvalSubmission, getDefaultApprovalTemplate('en'), approvalEnCtx, '', '#1e3a5f'),
    },
    {
      file: 'approval-bilingual.pdf',
      html: buildBilingualHtml(
        approvalSubmission,
        getDefaultApprovalTemplate('he'),
        getDefaultApprovalTemplate('en'),
        approvalHeCtx,
        approvalEnCtx,
        '',
        '#1e3a5f'
      ),
    },
    {
      file: 'protocol-he.pdf',
      html: buildProtocolHtml(protocol, 'he', protocolContext),
    },
    {
      file: 'protocol-en.pdf',
      html: buildProtocolHtml(protocol, 'en', protocolContext),
    },
    {
      file: 'protocol-bilingual.pdf',
      html: buildBilingualProtocolHtml(protocol, protocolContext),
    },
  ]

  for (const item of files) {
    await renderHtmlToPdf(item.html, path.join(outputDir, item.file))
    // eslint-disable-next-line no-console
    console.log(`Generated ${item.file}`)
  }
}

generatePreviews().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('Failed to generate previews:', err)
  process.exit(1)
})
