/**
 * EthicFlow — protocol PDF rendering tests.
 */

import path from 'path'
import os from 'os'
import fs from 'fs/promises'
import { jest } from '@jest/globals'
import { renderHtmlToPdf } from '../src/services/pdf/renderer.js'
import { buildProtocolHtml, buildBilingualProtocolHtml } from '../src/services/pdf/templates/protocol.js'

let PDFParseClass = null

/**
 * Lazily resolves PDF parser class from ESM package.
 * @returns {Promise<any>}
 */
async function getPDFParseClass() {
  if (PDFParseClass) return PDFParseClass
  const mod = await import('pdf-parse')
  PDFParseClass = mod.PDFParse
  return PDFParseClass
}

const protocol = {
  id: 'protocol-test-1',
  title: 'פרוטוקול ועדת אתיקה אפריל 2026',
  contentJson: {
    sections: [
      { heading: 'פתיחה', content: 'הישיבה נפתחה בשעה 09:00.' },
      { heading: 'החלטות', content: 'הבקשה ETH-2026-1001 אושרה.' },
    ],
  },
  signatures: [
    { id: '1', status: 'SIGNED', user: { fullName: 'ד"ר מרים כהן' } },
    { id: '2', status: 'PENDING', user: { fullName: 'Prof. Daniel Katz' } },
  ],
}

const context = {
  brandPrimary: '#1e3a5f',
  he: {
    issueDate: 'הופק: 20/04/2026',
    meetingDate: '19/04/2026',
    statusLabel: 'ממתין לחתימות',
    titleLabel: 'פרוטוקול ועדת אתיקה',
    meetingLabel: 'תאריך ישיבה',
    statusFieldLabel: 'סטטוס',
    footer: 'מסמך זה הופק על ידי מערכת EthicFlow • 20/04/2026',
    institutionName: 'המרכז האקדמי לב',
  },
  en: {
    issueDate: 'Generated: 20 April 2026',
    meetingDate: '19 April 2026',
    statusLabel: 'Pending Signatures',
    titleLabel: 'Ethics Committee Protocol',
    meetingLabel: 'Meeting Date',
    statusFieldLabel: 'Status',
    footer: 'Generated by EthicFlow • 20 April 2026',
    institutionName: 'Lev Academic Center',
  },
}

/**
 * Renders HTML to PDF and parses text.
 * @param {string} html
 * @returns {Promise<{ text: string, size: number }>}
 */
async function renderAndParse(html) {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ef-protocol-test-'))
  const outputPath = path.join(tmpDir, 'protocol.pdf')
  try {
    await renderHtmlToPdf(html, outputPath)
    const buffer = await fs.readFile(outputPath)
    const PDFParse = await getPDFParseClass()
    const parser = new PDFParse({ data: buffer })
    const parsed = await parser.getText()
    await parser.destroy().catch(() => {})
    return { text: parsed.text, size: buffer.length }
  } finally {
    await fs.rm(tmpDir, { recursive: true, force: true }).catch(() => {})
  }
}

describe('protocol PDFs', () => {
  jest.setTimeout(90000)

  it('renders Hebrew protocol PDF', async () => {
    const html = buildProtocolHtml(protocol, 'he', context)
    const { text, size } = await renderAndParse(html)
    expect(size).toBeGreaterThan(5000)
    expect(text).toContain('ETH-2026-1001')
    expect(text).toContain('פרוטוקול')
  })

  it('renders English protocol PDF', async () => {
    const html = buildProtocolHtml(protocol, 'en', context)
    const { text, size } = await renderAndParse(html)
    expect(size).toBeGreaterThan(5000)
    expect(text).toContain('Meeting Date')
    expect(text).toContain('Pending Signatures')
  })

  it('renders bilingual protocol PDF', async () => {
    const html = buildBilingualProtocolHtml(protocol, context)
    const { text, size } = await renderAndParse(html)
    expect(size).toBeGreaterThan(6000)
    expect(text).toContain('Meeting Date')
    expect(text).toContain('ETH-2026-1001')
  })
})
