/**
 * EthicFlow — Icon registry
 * Central re-export of lucide-react icons used across the app.
 * All icons rendered monochrome; color/size controlled by consumers.
 * Default stroke is 1.75 and color inherits from currentColor.
 * Keep imports explicit to enable tree-shaking.
 */

export {
  // Navigation / shell
  Home,
  FileText,
  Send,
  Search,
  Scale,
  FolderOpen,
  Calendar,
  CalendarDays,
  Bell,
  Shield,
  AlertTriangle,
  AlertCircle,
  Users,
  BarChart3,
  Compass,
  Settings,
  Menu,
  X,
  LogOut,
  LogIn,
  UserCircle2,
  ClipboardList,
  Inbox,
  Eye,
  EyeOff,
  KeyRound,
  Mail,
  Lock,
  // Actions
  Plus,
  Minus,
  Check,
  CheckCircle2,
  XCircle,
  Trash2,
  Pencil,
  Copy,
  Download,
  Upload,
  Filter,
  SlidersHorizontal,
  RefreshCw,
  MoreVertical,
  MoreHorizontal,
  // Direction (RTL-aware usage at site)
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  // Layout
  Grid3x3,
  List,
  LayoutDashboard,
  Sidebar as SidebarIcon,
  // Status / feedback
  Info,
  HelpCircle,
  Clock,
  Timer,
  Hourglass,
  Loader2,
  // Misc
  Sparkles,
  FileCheck2,
  FilePlus2,
  Signature,
  Building2,
  GraduationCap,
  BookOpen,
  Globe,
  Languages,
  Hand,
  Star,
  Target,
  TrendingUp,
  TrendingDown,
  Activity,
} from 'lucide-react'
